# goal
std_msgs/Header header
actionlib_msgs/GoalID goal_id
string controller
control_msgs/FollowJointTrajectoryActionGoal joint
---
# result
control_msgs/FollowJointTrajectoryActionResult action_result
---
# feedback
control_msgs/FollowJointTrajectoryActionFeedback action_feedback
