# goal
std_msgs/Header header
actionlib_msgs/GoalID goal_id
string controller
control_msgs/FollowJointTrajectoryGoal joint
---
# result
control_msgs/FollowJointTrajectoryResult result
---
# feedback
control_msgs/FollowJointTrajectoryFeedback feedback
