controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home
  - group: end_effector
    pose: open