manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5e_shoulder_pan_joint
    - ur5e_shoulder_lift_joint
    - ur5e_elbow_joint
    - ur5e_wrist_1_joint
    - ur5e_wrist_2_joint
    - ur5e_wrist_3_joint
  gains:
    ur5e_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
end_effector_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - finger_joint
  gains:
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1